### ISSUE TITLE
Implement first version of personal website

### ISSUE THREAD

**Issue by jensmeindertsma** [jensmeindertsma/jensmeindertsma.com#1]
This issue is a tracking issue for all the work that needs to be done to ship the first version of my personal website.

### Tasks
- [ ] Set up Remix application
- [ ] Design basic layout and home page mobile-first
- [ ] Add social links
- [ ] Add Spotify widget
- [ ] Implement blog
