### ISSUE TITLE
Deploy first version of personal website

### ISSUE THREAD

**Issue by jensmeindertsma** [jensmeindertsma/jensmeindertsma.com#3]
This issue is the main tracking issue for the first version of my personal website.

### Todo
- [ ] #1 
- [ ] Design the home page
- [ ] Add Spotify widget
- [ ] Add social links
- [ ] Add dark mode
